version: "3.9"

services: 
  django:
    container_name: django-dev
    build:
      context: ../../
      dockerfile: docker/dev/Dockerfile.back
    ports:
      - "8000:8000"
    volumes: 
      - ../../back/:/home/app/django/back/
    env_file:
      - ./.env
    command:
      python manage.py runserver 0.0.0.0:8000

  vue:
    container_name: vue-dev
    build:
      context: ../../
      dockerfile: docker/dev/Dockerfile.front
    ports:
      - "8080:8080"
    volumes:
      - ../../front/:/home/app/vue/
    depends_on:
      - django
    command:
      yarn serve

  redis:
    image: redis:alpine
    restart: always

  celery:
    restart: always
    build:
      context: ../../
      dockerfile: docker/dev/Dockerfile.back
    command:
      celery -A back worker -l info
    volumes:
      - ../../back/:/home/app/django/back/
    env_file:
      - ./.env
    depends_on:
      - redis
      - django

  