version: "3.9"

volumes:
  postgres-data:

services: 
  server:
    container_name: server
    build:
      context: ../../
      dockerfile: docker/prod/Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    command: 
      gunicorn back.wsgi:application --bind 0.0.0.0:8000
    depends_on:
      - db

  db:
    image: postgres
    volumes: 
      - postgres-data:/var/data/db  
    env_file:
      - ./.env
