version: "3.9"

services: 
  django:
    container_name: django-dev
    build:
      context: ../../
      dockerfile: docker/docker-dev/Dockerfile.backend
    ports:
      - "8000:8000"
    volumes: 
      - ../../backend/:/home/app/django/
    env_file:
      - ./.env
    command: 
      python manage.py runserver 0.0.0.0:8000

  vue:
    container_name: vue-dev
    build:
      context: ../../
      dockerfile: docker/docker-dev/Dockerfile.frontend
    ports:
      - "8080:8080"
    volumes:
      - ../../frontend/:/home/app/vue/
    depends_on:
      - django
    command:
      npm run serve

