FROM python:3.10.4

WORKDIR /usr/src/app/

COPY backend/requirements.txt .

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

RUN pip install --upgrade pip
RUN pip install -r requirements.txt

WORKDIR /home/app/django

COPY backend .

