# Generated by Django 4.0.4 on 2022-06-03 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QrCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('redirect_url', models.TextField(max_length=8192)),
                ('const_url', models.CharField(max_length=255)),
                ('img_url', models.CharField(max_length=255)),
            ],
        ),
    ]
