# Generated by Django 4.0.4 on 2022-05-28 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qr', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='session',
            old_name='session_hash',
            new_name='hash',
        ),
        migrations.AlterField(
            model_name='user',
            name='password_hash',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
