# Generated by Django 4.0.4 on 2022-05-28 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qr', '0002_rename_session_hash_session_hash_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='authType',
            field=models.CharField(blank=True, default='n', max_length=1),
        ),
    ]
